FROM node:lts-alpine

WORKDIR /app

# Copy package.json & package-lock.json files. sometime spackage-lock.json has issues when docker is running different version of different OS than where package-lock.json was created
COPY package*.json ./
COPY planetravel/package*.json ./planetravel/
COPY planetravelapis/package*.json ./planetravelapis/

# Install dependencies
RUN npm run install-client --prefix ./
RUN npm run install-server --prefix ./

# Copy source code
COPY planetravel/ ./planetravel/
COPY planetravelapis/ ./planetravelapis/

# Build frontend
RUN npm run buildv --prefix planetravel

# Create public directory in backend and copy build artifacts
RUN mkdir -p planetravelapis/public
RUN cp -r planetravel/dist/* planetravelapis/public/

# Set user
USER node

# Expose port
EXPOSE 8000

# Start backend server
CMD ["npm", "start", "--prefix", "planetravelapis"]